services:
  fasalsarthi_live:
    build: .
    container_name: fasalsarthi_live
    environment:
      APP_ENV: production
      APP_DEBUG: false
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: fasalsarthi
      DB_USERNAME: pgsql
      DB_PASSWORD: Developer@014789
    volumes:
      - storage_data:/var/www/html/storage
    networks:
      - fasalsarthi_network

  fasalsarthi_staging:
    build: .
    container_name: fasalsarthi_staging
    environment:
      APP_ENV: production
      APP_DEBUG: false
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: fasalsarthi
      DB_USERNAME: pgsql
      DB_PASSWORD: Developer@014789
    volumes:
      - storage_data:/var/www/html/storage
    networks:
      - fasalsarthi_network

  db:
    image: postgres:15
    container_name: fasalsarthi_postgres
    restart: always
    environment:
      POSTGRES_DB: fasalsarthi
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: Developer@014789
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fasalsarthi_network

  nginx:
    image: nginx:latest
    container_name: fasalsarthi_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - fasalsarthi_live
    networks:
      - fasalsarthi_network

volumes:
  db_data:
  storage_data:

networks:
  fasalsarthi_network:
    driver: bridge
