version: "3.9"

services:
  laravel_blue:
    build: .
    container_name: laravel_blue
    environment:
      APP_ENV: production
      APP_DEBUG: false
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: fasalsarthi
      DB_USERNAME: pgsql
      DB_PASSWORD: Developer@014789
    networks:
      - fasalsarthi_network

  laravel_green:
    build: .
    container_name: laravel_green
    environment:
      APP_ENV: production
      APP_DEBUG: false
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: fasalsarthi
      DB_USERNAME: pgsql
      DB_PASSWORD: Developer@014789
    networks:
      - fasalsarthi_network

  db:
    image: postgres:15
    container_name: fasalsarthiweb_postgres
    restart: always
    environment:
      POSTGRES_DB: fasalsarthi
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: Developer@014789
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fasalsarthi_network

  nginx:
    image: nginx:latest
    container_name: fasalsarthiweb_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - laravel_blue
    networks:
      - fasalsarthi_network

volumes:
  db_data:

networks:
  fasalsarthi_network:
    driver: bridge
